=== johnollier/register-metadata/local-authority-eng-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "properties": {
        "end-date": {
            "description": "The date a record stopped being applicable.",
            "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$",
            "type": "string"
        },
        "local-authority-eng": {
            "description": "The local authority's ISO 3166-1 alpha3 code. Unique codes have been created for local authorities that don't have an existing ISO code.",
            "type": "string"
        },
        "local-authority-type": {
            "description": "The type of a local government organisation.",
            "type": "string"
        },
        "name": {
            "description": "The commonly-used name of a record.",
            "type": "string"
        },
        "official-name": {
            "description": "The official or technical name of a record.",
            "type": "string"
        },
        "start-date": {
            "description": "The date a record first became relevant to a register.",
            "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$" ,
            "type": "string"
        },
        "website": {
            "description": "Website for register entry.",
            "format": "uri",
            "type": "string"
        }
    },
    "required": [
        "local-authority-eng"
    ],
    "title": "local-authority-eng",
    "type": "object"
}

=== johnollier/register-metadata/local-authority-item.json
[
    {
        "local-authority-eng": "BAS",
        "local-authority-type": "UA",
        "name": "Bath and North East Somerset",
        "official-name": "Bath and North East Somerset Council",
        "start-date": "1996-04-01"
    },
    {
        "local-authority-eng": "BBD",
        "local-authority-type": "UA",
        "name": "Blackburn",
        "official-name": "Blackburn",
        "start-date": "1996-04-01"
    }
]
